#+TITLE: UofT Notes

This is a repository for the notes that I took while at the University of toronto. The following is a list of the courses covered in this repository.

| Course | Instructor         | Time  | Note File         |
|--------+--------------------+-------+-------------------|
| CSC110 | [[http://mariobadr.com][Mario Badr]]         | 2020F | [[csc110/csc110.pdf]] |
| CSC111 | [[https://www.cs.toronto.edu/~david/][David Liu]]          | 2021S | [[csc111/csc111.pdf]] |
| MAT137 | [[https://www.gatheringus.com/memorial/alfonso-gracia-saz/7329?locale=en&c=937][Alfonso Gracia-Saz]] | 2020Y | [[mat137/mat137.pdf]] |
| CSC236 | [[https://cs.toronto.edu/~heap][Daniel Heap]]        | 2021S | [[csc236/csc236.pdf]] |


* Contributing

** Editing

*** ORG Mode

Some of the PDF files are written in ORG mode (~.ORG~). This is most accessible through GNU Emacs but there are other ways to write it (vim plugins, vscode extensions, etc.). If you need exact emacs configuration, my dotfiles are public and my emacs configuration is [[https://github.com/hisbaan/dotfiles/blob/master/.doom.d/config.el][here]].

In emacs, the key combination for compiling the ORG file into a LaTeX pdf is ~C-c C-e m e l p~ (or ~SPC m e l p~ with evil mode bindings).

*** LaTeX

Some other PDF files are written in LaTeX. For compilation, I use LuaLaTeX through LaTeXmk. To generate the PDF for a file called ~example.tex~, run ~latexmk -lualatex -shell-escape example.tex~. This will generate ~example.pdf~.

** Compiling PDFs

*** CSC110

Navigate to the ~uoft-notes/csc110/src~ directory then build every PDF from the ORG source file using GNU Emacs. After this, go to the ~uoft-notes/csc110~ directory and run the following commands.

#+begin_src sh
rm csc110.pdf
pdftk src/*.pdf cat output csc110.pdf
#+end_src

*** CSC111

Navigate to the ~uoft-notes/csc111/src~ directory then build every PDF from the ORG source file using GNU Emacs. After this, go to the ~uoft-notes/csc111~ directory and run the following commands.

#+begin_src sh
rm csc111.pdf
pdftk src/*.pdf cat output csc111.pdf
#+end_src

*** MAT137

Navigate to the ~uoft-notes/mat137~ directory and run the following command.

#+begin_src sh
latexmk -lualatex -shell-escape mat137.tex
#+end_src

*** CSC236

Navigate to the ~uoft-notes/csc236/src~ directory then build every PDF from the ORG source file using GNU Emacs. After this, go to the ~uoft-notes/csc236~ directory and run the following commands.

#+begin_src sh
rm csc236.pdf
pdftk src/*.pdf cat output csc236.pdf
#+end_src
