#+TITLE: CSC236 Lecture 05: Recurrences, Structural Induction
#+date: September 24, 2021
#+author: Hisbaan Noorani
#+setupfile: setup.org

* Recursively defined function

Recall:
\[f(n) = \begin{cases} 1 & n = 0 \\ 2 & n = 1 \\ f(n - 1) + f(n - 2) & n > 1 \end{cases}\]
For comparison, let
\[
  r_{1} = \frac{1 + \sqrt{5}}{2},~
  r_{2} = \frac{1 - \sqrt{5}}{2},~
  a = \frac{\sqrt{5} + 3}{2 \sqrt{5}},~
  b = \frac{\sqrt{5} - 3}{2 \sqrt{5}}
\]
\dots and define
\[f'(n) = ar_{1}^{n} + br_{2}^{n}\]
Compare the first few values of \(f(n)\) to the first few values of \(f'(n)\)
\begin{align*}
    f(0) = 1 &,\quad f'(0) = 1 \\
    f(1) = 2 &,\quad f'(1) = 2  \\
    f(2) = 5 &,\quad f'(2) = 5  \\
    f(3) = 8 &,\quad f'(3) = 8 \\
    f(4) = 13 &,\quad f'(4) = 13
\end{align*}

* Prove that \(\forall n \in \N, f(n) = f'(n)\)

\(\forall n \in \N\), define \(P(n)\) by \(f(n) = f'(n)\).

Prove by complete induction that \(\forall n \in \N, P(n)\). It helps to verify \(1 + r_{1} = r_{1}^2\) and \(1 + r_{2} = r_{2}^{2}\).

#+begin_latex
Let \(n \in \N\). Assume the induction hypothesis, \(\forall k \in \N \st k < n\) has \(f(k) = f'(k)\).

\begin{itemize}
  \item
        Case \(n > 1\):
        \begin{align*}
          f(n) &= f(n - 1) + f(n - 2) && \text{(by definition)} \\
               &= ar_{1}^{n - 1} + br_{2}^{n - 1} + ar_{1}^{n - 2} + ar_{2}^{n - 2}&&\text{(by IH, since \(0 \leq n - 2, n - 1 < n\))} \\
               &= a \br{r_{1}^{n - 2} + r_{1}^{n - 1}} + b \br{r_{2}^{n - 2} + r_{2}^{n - 1}} \\
               &= a \br{r_{1}^{n - 2}} \br{1 + r_{1}} + b \br{r_{2}^{n - 2}} \br{1 + r_{2}} \\
               &= a \br{r_{1}^{n - 2}} \br{r_{1}^{2}} + b \br{r_{2}^{n - 2}} \br{r_{2}^{2}} \\
               &= ar_{1}^{n} + br_{2}^{n} \\
               &= f'(n)
        \end{align*}
        And thus \(\forall n > 1, P(n)\) holds.
  \item
        Case \(n = 0\):
        \(f(0) = 1 = f'(0)\), by evaluating \(f'(0)\) so \(P(0)\) holds.
  \item
        Case \(n = 1\):
        \(f(1) = 2 = f'(1)\), by evaluating \(f'(1)\) so \(P(1)\) holds.
\end{itemize}

Thus, in all possible cases, \(P(n)\) holds. \(\blacksquare\)
#+end_latex
* Define sets inductively

One way to define the natural numbers:
- \(\N\): The smallest set such that
  1. \(0 \in \N\)
  2. \(n \in \N \implies n + 1 \in \N\)
By *smallest* we mean \(\N\) has no proper subsets that satisfy these two conditions. If we leave out *smallest*, what other sets satisfy the definition? \(\Q, \R, \C, \Z, \text{ etc.}\)

* What can you do with it?

The definition on the previous page defined the simplest natural number (0) and the rule to produce new natural numbers from old (add 1). Proof using Mathematical Induction work by showing that 0 has some property, and then that the rule to produce natural numbers preserves the property, that is
1. show that \(P(0)\) is true for basis, 0.
2. Prove that \(\forall n \in \N, P(n) \implies P(n + 1)\).

* Other structurally-defined sets

Define \(\mathcal{E}\): The smallest set such that

1. \(x, y, z \in \mathcal{E}\)
2. \(e_{1}, e_{2} \in \mathcal{E} \implies (e_{1} + e_{2}), (e_{1} - e_{2}), (e_{1} \times e_{2}), (e_{1} \div e_{2}) \in \mathcal{E}\)
Form some expressions in \(\mathcal{E}\). Count the number of variables (symbols from \(\{x, y, z\}\)) and the number of operators symbols from \(\{+, -, \times, \div\}\). Make a conjecture

\((x + y), (x \times y) \in \mathcal{E}\)

\(((x + y) \times (x \times y)) \in \mathcal{E}\)

Let \(\mathrm{vr}(e)\) count the number of variables in \(e\) and let \(\mathrm{op}(e)\) count the number of operators in \(e\).
\[\forall e \in \mathcal{E}, \mathrm{vr}(e) = \mathrm{op}(e) + 1\]
* Structural induction

To prove that a property is true for all \(e \in \mathcal{E}\), parallel the recursive set definition:

- *Verify the base case(s)*: Show that the property is true for the simplest members, \(\{x, y, z\}\), that is show \(P(x), P(y), \tand P(z)\).

- *Inductive step*: Let \(e_{1}\) and \(e_{2}\) be arbitrary elements of \(\mathcal{E}\). Assume \(H(\cbr{e_{1}, e_{2})}\): \(P(e_{1})\) and \(P(e_{2})\), that is \(e_{1}\) and \(e_{2}\) have the property.

  + *Show that \(C(\cbr{e_{1}, e_{2}})\) follows:*

    All possible combinations of \(e_{1}\) and \(e_{2}\) have the property, that is \(P((e_{1} + e_{2})), P((e\)
